## Create the machine learning  

### Import the relevant libraries

In [1]:
import numpy as np
import tensorflow as tf

### Data

In [2]:
npz = np.load("C:/IFOOD/ifood_data_train.npz")
train_inputs = npz['inputs'].astype(np.float)
train_targets = npz['targets'].astype(np.int)

npz = np.load("C:/IFOOD/ifood_data_validation.npz")
validation_inputs, validation_targets = npz['inputs'].astype(np.float), npz['targets'].astype(np.int)

npz = np.load("C:/IFOOD/ifood_data_test.npz")
test_inputs, test_targets = npz['inputs'].astype(np.float), npz['targets'].astype(np.int)

<ipython-input-2-151cd37ce3e7>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_inputs = npz['inputs'].astype(np.float)
<ipython-input-2-151cd37ce3e7>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_targets = 

### Model 

Outline, optimizers, loss, early stopping and training

In [34]:
output_size = 2
hidden_layer_size = 50


model = tf.keras.Sequential([
    
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 1st hidden layer
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 2nd hidden layer
    tf.keras.layers.Dense(output_size, activation='softmax') # output layer
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
### Training

# set the batch size
batch_size = 100

# set a maximum number of training epochs
max_epochs = 100

#Setting early stopping
early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

#fitting the model
model.fit(train_inputs, 
          train_targets, 
          batch_size=batch_size, 
          epochs=max_epochs, 
          callbacks=[early_stopping], 
          validation_data=(validation_inputs, validation_targets),
          verbose = 2 
          )  

Epoch 1/100
6/6 - 0s - loss: 0.6647 - accuracy: 0.6015 - val_loss: 0.6861 - val_accuracy: 0.5909 - 461ms/epoch - 77ms/step
Epoch 2/100
6/6 - 0s - loss: 0.5804 - accuracy: 0.6823 - val_loss: 0.6366 - val_accuracy: 0.6818 - 41ms/epoch - 7ms/step
Epoch 3/100
6/6 - 0s - loss: 0.5307 - accuracy: 0.7180 - val_loss: 0.6109 - val_accuracy: 0.6970 - 33ms/epoch - 6ms/step
Epoch 4/100
6/6 - 0s - loss: 0.4927 - accuracy: 0.7763 - val_loss: 0.5976 - val_accuracy: 0.6970 - 37ms/epoch - 6ms/step
Epoch 5/100
6/6 - 0s - loss: 0.4593 - accuracy: 0.7914 - val_loss: 0.5911 - val_accuracy: 0.7424 - 37ms/epoch - 6ms/step
Epoch 6/100
6/6 - 0s - loss: 0.4329 - accuracy: 0.8102 - val_loss: 0.5826 - val_accuracy: 0.7424 - 34ms/epoch - 6ms/step
Epoch 7/100
6/6 - 0s - loss: 0.4105 - accuracy: 0.8327 - val_loss: 0.5756 - val_accuracy: 0.7424 - 39ms/epoch - 6ms/step
Epoch 8/100
6/6 - 0s - loss: 0.3903 - accuracy: 0.8459 - val_loss: 0.5722 - val_accuracy: 0.7424 - 36ms/epoch - 6ms/step
Epoch 9/100
6/6 - 0s - loss: 0

## Test the model 

In [35]:
test_loss, test_accuracy = model.evaluate(test_inputs, test_targets)

3/3 [==============================] - 0s 5ms/step - loss: 0.4649 - accuracy: 0.7647


In [36]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.46. Test accuracy: 76.47%


## Obtain the probability  

In [37]:
model.predict(test_inputs)

array([[0.5880475 , 0.41195256],
       [0.02084344, 0.9791566 ],
       [0.84913146, 0.15086854],
       [0.44876558, 0.5512344 ],
       [0.66991717, 0.3300828 ],
       [0.1453082 , 0.8546918 ],
       [0.04481385, 0.9551861 ],
       [0.9370826 , 0.06291735],
       [0.2609915 , 0.7390085 ],
       [0.77435285, 0.22564708],
       [0.9663059 , 0.03369405],
       [0.05465418, 0.94534576],
       [0.95748526, 0.0425147 ],
       [0.5925856 , 0.40741438],
       [0.33074912, 0.6692509 ],
       [0.07624041, 0.9237596 ],
       [0.8398872 , 0.16011274],
       [0.400087  , 0.59991306],
       [0.77823764, 0.22176236],
       [0.24181083, 0.75818914],
       [0.7401833 , 0.25981677],
       [0.05483229, 0.94516766],
       [0.7443433 , 0.25565675],
       [0.7927945 , 0.20720543],
       [0.84293646, 0.15706354],
       [0.10239004, 0.8976099 ],
       [0.525507  , 0.47449303],
       [0.8436092 , 0.15639076],
       [0.23476936, 0.7652306 ],
       [0.72865397, 0.271346  ],
       [0.

In [38]:
model.predict(test_inputs)[:,1].round(0)

array([0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1.],
      dtype=float32)

In [39]:
np.argmax(model.predict(test_inputs),axis=1)

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1], dtype=int64)

In [40]:
model.save("C:/IFOOD/ifood_data_validation/audiobooks_model.h5") 